### PR TITLE
Fix SPI device and update Python tools

### PR DESCRIPTION
**Pull request by rivos-eblot**

### CODE REVIEW

**Comment by rivos-eblot** [comment]
@jwnrt I think https://github.com/lowRISC/qemu/pull/91/commits/dd781daf5d7e8d7cb756af280ed89b0c744ef889 applies to your branch as well. Without this fix, there may be a interrupt raised for CMD FIFO not empty and no command in the FIFO :)

**Comment by jwnrt** [comment]
Thanks, that does look relevant. @AlexJones0, I'm going to be on vacation starting in 30 minutes, would you mind cherry picking this? :)

**Comment by rivos-eblot** [comment]
> I'm going to be on vacation starting in 30 minutes

Enjoy!

**Comment by AlexJones0** [comment]
> Thanks, that does look relevant. @AlexJones0, I'm going to be on vacation starting in 30 minutes, would you mind cherry picking this? :)

Sure, I'll open a separate PR cherry-picking that commit across.

**Review by loiclefort — APPROVED** [review]
LGTM (reviewed internally)

**Pull request merged**
